steps:
  # Build and Deploy Flask Backend
  - name: 'gcr.io/cloud-builders/docker'
    dir: flask_backend
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud', 'run', 'deploy', 'flask-backend',
      '--image=gcr.io/$PROJECT_ID/flask-backend',
      '--platform=managed',
      '--region=us-central1',
      '--allow-unauthenticated'
    ]

  # Build and Deploy React Frontend
  - name: 'gcr.io/cloud-builders/docker'
    dir: react_frontend
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-frontend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-frontend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud', 'run', 'deploy', 'react-frontend',
      '--image=gcr.io/$PROJECT_ID/react-frontend',
      '--platform=managed',
      '--region=us-central1',
      '--allow-unauthenticated'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
